apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: studentapp-frontend-hpa
  labels:
    app: studentapp-frontend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: studentapp-frontend
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50